### ISSUE TITLE
Exceeding maximum number of iterations

### ISSUE THREAD

**Issue by ggdhines** [CitizenScienceInAstronomyWorkshop/pyIBCC#12]
With even relatively small input files I'm getting an "exceeded maximum number of iterations results". As far as I can tell the results are still "reasonable" so honestly not sure if this is an error or not. Even when I don't get that error things seem to take more iterations than it should. For example, if I have just 20 lines in my input file I get the following output:
WARNING:root:IBCC iteration 2 absolute change was -1.05617041708e-05. Possible bug or rounding error?
Optimization terminated successfully.
         Current function value: 25.825665
         Iterations: 326
         Function evaluations: 524
I actually get a lot of those warnings (almost 200 or so) which seems like a for just 20 lines of input.

With 200 lines of input, I get
WARNING:root:IBCC iteration 2 absolute change was -2.11809491759e-05. Possible bug or rounding error?
Warning: Maximum number of function evaluations has been exceeded.
The maximum number of evaluations warnings doesn't always happen.
Below is a link to the config file I used plus the example input for 20 lines and 200 lines.
https://gist.github.com/ggdhines/e973756002bb4083c887

**Comment by edwinrobots** [comment]
The messages about function evaluations come from the hyper-parameter optimisation step. This step is doing a search through different values of alpha0 and nu0 to maximise the model evidence, starting with the values you specify in the config file. Some values it chooses cause the warnings to appear. With the longer input file, the search algorithm doesn't converge within the specified number of iterations.

This step is not necessary if you have reasonable hyperparameters set in your config file. It can help when you are unsure about which values to use, and for datasets that seem to be very sensitive to the exact choice of alpha0. I've switched this off by default for now, as it isn't a very user-friendly feature, and needs some work to improve it.
